export const USER_POLICY_REGISTRY = {
  ALREDY_EXISTS: 'MODULE::APPLICATION::POLICY::USER::ALREDY_EXISTS',
  SHOULD_EXISTS: 'MODULE::APPLICATION::POLICY::USER::SHOULD_EXISTS',
  IS_VALID_PASSWORD: 'MODULE::APPLICATION::POLICY::USER::HASH_PASSWORD',
};
