export const TUTORIAL_REGISTRY = {
  REPOSITORY: {
    PRISMA: 'MODULE::TUTORIAL::REPOSITORY::PRISMA',
  },
  SERVICE: {
    MAIN: 'MODULE::TUTORIAL::SERVICE::MAIN',
  },
  USE_CASE: {
    CREATE: 'MODULE::TUTORIAL::USE_CASE::CREATE',
    UPDATE: 'MODULE::TUTORIAL::USE_CASE::UPDATE',
    DELETE: 'MODULE::TUTORIAL::USE_CASE::DELETE',
    FILTER: {
      BY: {
        AUTHOR: 'MODULE::TUTORIAL::USE_CASE::FILTER::BY::AUTHOR',
        TITLE: 'MODULE::TUTORIAL::USE_CASE::FILTER::BY::TITLE',
        KEYWORD: 'MODULE::TUTORIAL::USE_CASE::FILTER::BY::KEYWORD',
      },
    },
    LIST: {
      ALL: 'MODULE::TUTORIAL::USE_CASE::LIST::ALL',
    },
  },
};
